from typing import Any

class _Program:
    def input(self, data: Any) -> _ProgramWithInput: ...

class _ProgramWithInput:
    def first(self) -> Any: ...
    def all(self) -> list[Any]: ...

def compile(query: str) -> _Program: ...
