from __future__ import annotations

from lxml.etree import _Element

class BaseExtension:
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, feed: _Element) -> _Element: ...
    def extend_atom(self, feed: _Element) -> _Element: ...

class BaseEntryExtension(BaseExtension): ...
