from __future__ import annotations

from feedgen.ext.base import BaseEntryExtension, BaseExtension
from lxml.etree import _Element

class DcBaseExtension:
    def dc_contributor(self, contributor: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_coverage(self, coverage: str | None = None, replace: bool = True) -> str | None | DcBaseExtension: ...
    def dc_creator(self, creator: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_date(self, date: str | list[str] | None = None, replace: bool = True) -> list[str] | None | DcBaseExtension: ...
    def dc_description(self, description: str | None = None, replace: bool = True) -> str | None | DcBaseExtension: ...
    def dc_format(self, format: str | None = None, replace: bool = True) -> str | None | DcBaseExtension: ...
    def dc_identifier(self, identifier: str | None = None, replace: bool = True) -> str | None | DcBaseExtension: ...
    def dc_language(self, language: str | None = None, replace: bool = True) -> str | None | DcBaseExtension: ...
    def dc_publisher(self, publisher: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_relation(self, relation: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_rights(self, rights: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_source(self, source: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_subject(self, subject: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...
    def dc_title(self, title: str | None = None, replace: bool = True) -> str | None | DcBaseExtension: ...
    def dc_type(self, type: str | list[str] | None = None, replace: bool = False) -> list[str] | None | DcBaseExtension: ...

class DcExtension(DcBaseExtension, BaseExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, feed: _Element) -> _Element: ...
    def extend_atom(self, feed: _Element) -> _Element: ...

class DcEntryExtension(DcBaseExtension, BaseEntryExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, entry: _Element) -> _Element: ...
    def extend_atom(self, entry: _Element) -> _Element: ...
