from __future__ import annotations

import numbers

from feedgen.ext.base import BaseEntryExtension, BaseExtension
from lxml.etree import _Element

class GeoRSSPolygonInteriorWarning(Warning): ...
class GeoRSSGeometryError(ValueError): ...

class GeoExtension(BaseExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, feed: _Element) -> _Element: ...
    def extend_atom(self, feed: _Element) -> _Element: ...

class GeoEntryExtension(BaseEntryExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, entry: _Element) -> _Element: ...
    def extend_atom(self, entry: _Element) -> _Element: ...

    def point(self, point: str | None = None) -> str | None | GeoEntryExtension: ...
    def line(self, line: str | None = None) -> str | None | GeoEntryExtension: ...
    def polygon(self, polygon: str | None = None) -> str | None | GeoEntryExtension: ...
    def box(self, box: str | None = None) -> str | None | GeoEntryExtension: ...
    def featuretypetag(self, featuretypetag: str | None = None) -> str | None | GeoEntryExtension: ...
    def relationshiptag(self, relationshiptag: str | None = None) -> str | None | GeoEntryExtension: ...
    def featurename(self, featurename: str | None = None) -> str | None | GeoEntryExtension: ...
    def elev(self, elev: numbers.Number | None = None) -> numbers.Number | None | GeoEntryExtension: ...
    def floor(self, floor: int | None = None) -> int | None | GeoEntryExtension: ...
    def radius(self, radius: numbers.Number | None = None) -> numbers.Number | None | GeoEntryExtension: ...
    def geom_from_geo_interface(self, geom: object) -> GeoEntryExtension: ...
