from __future__ import annotations

from typing import Literal

from feedgen.ext.base import BaseEntryExtension
from lxml.etree import _Element

class PodcastEntryExtension(BaseEntryExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, entry: _Element) -> _Element: ...
    def extend_atom(self, entry: _Element) -> _Element: ...

    def itunes_author(self, itunes_author: str | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_block(self, itunes_block: bool | str | None = None) -> bool | None | PodcastEntryExtension: ...
    def itunes_image(self, itunes_image: str | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_duration(self, itunes_duration: str | int | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_explicit(self, itunes_explicit: Literal["yes", "no", "clean"] | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_is_closed_captioned(self, itunes_is_closed_captioned: bool | Literal["yes", "no"] | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_order(self, itunes_order: int | None = None) -> int | None | PodcastEntryExtension: ...
    def itunes_subtitle(self, itunes_subtitle: str | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_summary(self, itunes_summary: str | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_season(self, itunes_season: int | None = None) -> int | None | PodcastEntryExtension: ...
    def itunes_episode(self, itunes_episode: int | None = None) -> int | None | PodcastEntryExtension: ...
    def itunes_title(self, itunes_title: str | None = None) -> str | None | PodcastEntryExtension: ...
    def itunes_episode_type(self, itunes_episode_type: Literal["full", "trailer", "bonus"] | None = None) -> str | None | PodcastEntryExtension: ...
