from __future__ import annotations

from typing import Literal

from feedgen.ext.base import BaseExtension
from lxml.etree import _Element

class PodcastExtension(BaseExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, feed: _Element) -> _Element: ...
    def extend_atom(self, feed: _Element) -> _Element: ...

    def itunes_author(self, itunes_author: str | None = None) -> str | None | PodcastExtension: ...
    def itunes_block(self, itunes_block: bool | str | None = None) -> bool | None | PodcastExtension: ...
    def itunes_category(
        self,
        itunes_category: dict[str, str] | list[dict[str, str]] | None = None,
        replace: bool = False,
        **kwargs: str,
    ) -> list[dict[str, str]] | None | PodcastExtension: ...
    def itunes_image(self, itunes_image: str | None = None) -> str | None | PodcastExtension: ...
    def itunes_explicit(self, itunes_explicit: Literal["yes", "no", "clean"] | None = None) -> str | None | PodcastExtension: ...
    def itunes_complete(self, itunes_complete: bool | Literal["yes", "no"] | None = None) -> str | None | PodcastExtension: ...
    def itunes_new_feed_url(self, itunes_new_feed_url: str | None = None) -> str | None | PodcastExtension: ...
    def itunes_owner(self, name: str | None = None, email: str | None = None) -> dict[str, str] | None | PodcastExtension: ...
    def itunes_subtitle(self, itunes_subtitle: str | None = None) -> str | None | PodcastExtension: ...
    def itunes_summary(self, itunes_summary: str | None = None) -> str | None | PodcastExtension: ...
    def itunes_type(self, itunes_type: Literal["episodic", "serial"] | None = None) -> str | None | PodcastExtension: ...
