from __future__ import annotations

from typing import Literal

from feedgen.ext.base import BaseEntryExtension, BaseExtension
from lxml.etree import _Element

class SyndicationExtension(BaseExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, feed: _Element) -> _Element: ...
    def extend_atom(self, feed: _Element) -> _Element: ...

    def update_period(self, value: Literal["hourly", "daily", "weekly", "monthly", "yearly"]) -> SyndicationExtension: ...
    def update_frequency(self, value: int) -> SyndicationExtension: ...
    def update_base(self, value: str) -> SyndicationExtension: ...

class SyndicationEntryExtension(BaseEntryExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, entry: _Element) -> _Element: ...
    def extend_atom(self, entry: _Element) -> _Element: ...
