from __future__ import annotations

from feedgen.ext.base import BaseEntryExtension, BaseExtension
from lxml.etree import _Element

class TorrentExtension(BaseExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, feed: _Element) -> _Element: ...
    def extend_atom(self, feed: _Element) -> _Element: ...

class TorrentEntryExtension(BaseEntryExtension):
    def extend_ns(self) -> dict[str, str]: ...
    def extend_rss(self, entry: _Element) -> _Element: ...
    def extend_atom(self, entry: _Element) -> _Element: ...

    def filename(self, torrent_filename: str | None = None) -> str | None | TorrentEntryExtension: ...
    def infohash(self, torrent_infohash: str | None = None) -> str | None | TorrentEntryExtension: ...
    def contentlength(self, torrent_contentlength: int | str | None = None) -> str | None | TorrentEntryExtension: ...
    def seeds(self, torrent_seeds: int | str | None = None) -> str | None | TorrentEntryExtension: ...
    def peers(self, torrent_peers: int | str | None = None) -> str | None | TorrentEntryExtension: ...
    def verified(self, torrent_verified: int | str | None = None) -> str | None | TorrentEntryExtension: ...
